from google.adk.agents import Agent, SequentialAgent
from sdr_agent.tools import search_lead, parse_leads_csv, score_lead, save_report


# ── Stage 1: Lead Research Agent ──────────────────────────────────────────────
research_agent = Agent(
    name="research_agent",
    model="gemini-2.5-flash-lite",
    instruction="""
    You are an elite B2B sales researcher.

    The user will give you:
    1. A product description
    2. A path to a CSV file of leads OR a single lead's details

    Your job:
    1. If a CSV path is given, use parse_leads_csv to load all leads.
    2. For each lead, use search_lead to research:
       - Their company: what they do, their size, recent news, funding
       - Their role: what problems they likely face day to day
       - Any recent trigger events (new funding, hiring spree, product launch)
    3. Write a research summary for each lead.

    Search queries to use per lead:
    - "[company name] company overview"
    - "[person name] [company] [role]"
    - "[company name] recent news 2024"

    Be specific and thorough. The quality of your research determines the quality of everything downstream.

    Write your output under: RESEARCH SUMMARY
    List each lead clearly with their research findings.
    """,
    tools=[parse_leads_csv, search_lead],
    output_key="research_summary",
)


# ── Stage 2: Lead Scorer Agent ────────────────────────────────────────────────
scorer_agent = Agent(
    name="scorer_agent",
    model="gemini-2.5-flash-lite",
    instruction="""
    You are a lead qualification specialist.

    You have this research on the leads:
    {research_summary}

    For each lead:
    1. Use score_lead to rate their fit with the product.
    2. Pass the company research summary and product description to score_lead.
    3. Assign HOT / WARM / COLD with a clear reason.
    4. Rank all leads from highest to lowest priority.

    Write your output under: LEAD SCORES
    Format each lead as:
    - Name | Company | Score | Reason
    """,
    tools=[score_lead],
    output_key="lead_scores",
)


# ── Stage 3: Email Writer Agent ───────────────────────────────────────────────
email_writer_agent = Agent(
    name="email_writer_agent",
    model="gemini-2.5-flash-lite",
    instruction="""
    You are an expert B2B sales copywriter. You write emails that get replies.

    You have:
    Research: {research_summary}
    Lead Scores: {lead_scores}

    For each lead (prioritise HOT first, then WARM, skip COLD):
    Write a personalised cold outreach email that:
    - Opens with something specific about THEM (not a generic opener)
    - References a real pain point their role/company likely faces
    - Connects that pain point to the product naturally
    - Has a single, low-friction call to action (15-min call, not "buy now")
    - Is under 150 words
    - Sounds human, not like a robot

    Rules:
    - Never start with "I hope this email finds you well"
    - Never use "synergy", "leverage", or "circle back"
    - Be direct and specific

    Write your output under: OUTREACH EMAILS
    Label each email clearly with the lead's name and score.
    """,
    output_key="outreach_emails",
)


# ── Stage 4: Objection Handler Agent ─────────────────────────────────────────
objection_agent = Agent(
    name="objection_agent",
    model="gemini-2.5-flash-lite",
    instruction="""
    You are a seasoned sales closer who has heard every objection.

    You have these outreach emails ready to send:
    {outreach_emails}

    For each HOT and WARM lead, prepare responses to these 3 common objections:
    1. "We already have a solution for this"
    2. "We don't have budget right now"
    3. "Send me more information" (the polite brush-off)

    Each response should:
    - Acknowledge their objection genuinely
    - Reframe it without being pushy
    - End with a soft next step
    - Be under 80 words

    Write your output under: OBJECTION RESPONSES
    Label each by lead name and objection type.
    """,
    output_key="objection_responses",
)


# ── Stage 5: Report Generator Agent ──────────────────────────────────────────
report_agent = Agent(
    name="report_agent",
    model="gemini-2.5-flash-lite",
    instruction="""
    You are a sales operations manager producing the final SDR report.

    Compile everything into one clean, structured report:

    Research: {research_summary}
    Scores: {lead_scores}
    Emails: {outreach_emails}
    Objection Responses: {objection_responses}

    Format the report as:

    # SDR REPORT
    Generated by AI Sales Development Rep Agent

    ## EXECUTIVE SUMMARY
    (How many leads, how many HOT/WARM/COLD, top recommendation)

    ## LEADS (ranked by score)
    For each lead:
    ### [Name] — [Company] — [SCORE]
    **Research:** ...
    **Why this score:** ...
    **Outreach Email:**
    ---
    [email here]
    ---
    **Objection Responses:**
    - If they say "we have a solution": ...
    - If they say "no budget": ...
    - If they say "send info": ...

    ## NEXT STEPS
    (Clear action items for the sales team)

    Then use save_report to save the report as sdr_report.md.
    """,
    tools=[save_report],
    output_key="final_report",
)


# ── Root Agent: Full SDR Pipeline ─────────────────────────────────────────────
root_agent = SequentialAgent(
    name="sdr_agent",
    description="An AI Sales Development Rep that researches leads, scores them, writes personalised emails, prepares objection responses, and produces a full SDR report.",
    sub_agents=[
        research_agent,
        scorer_agent,
        email_writer_agent,
        objection_agent,
        report_agent,
    ],
)